package valobj

import (
	corerr "github.com/Reddetk/SayMoDev/identy-service/internal/core/coreErrors"
	"github.com/Reddetk/SayMoDev/identy-service/internal/port/in"
)

// OAuthState - Value Object that carries PKCE and CSRF parameters
// generated by BC#1 for a single OAuth2 authorization request.
//
// Lifecycle: created in GET /iam/auth/oauth/google, stored server-side
// (signed cookie or server session), verified in callback.
//
// Spec: IAM Registration — OAuth2 (Google):
//   [1] "Frontend генерирует code_verifier"
//   [2] "state=<CSRF_token> ← случайный, хранится в сессии или cookie"
//   [5a] "Проверяет state (CSRF protection)"
//
// Invariants:
//   - csrfToken must be non-empty
//   - codeVerifier length: 43-128 chars (RFC 7636)
//   - codeChallenge must be non-empty (BASE64URL(SHA256(codeVerifier)))
//   - expiresAt must be a positive unix timestamp
type OAuthState struct {
	csrfToken     string
	codeVerifier  string
	codeChallenge string
	expiresAt     int64
}

// NewOAuthState constructs and validates an OAuthState VO.
func NewOAuthState(csrfToken, codeVerifier, codeChallenge string, expiresAt int64) (OAuthState, error) {
	if csrfToken == "" {
		return OAuthState{}, corerr.ErrOAuthStateCSRFTokenEmpty
	}
	verifierLen := len(codeVerifier)
	if verifierLen < 43 || verifierLen > 128 {
		return OAuthState{}, corerr.ErrPKCECodeVerifierInvalidLength
	}
	if codeChallenge == "" {
		return OAuthState{}, corerr.ErrPKCECodeChallengeEmpty
	}
	if expiresAt <= 0 {
		return OAuthState{}, corerr.ErrOAuthStateExpired
	}
	return OAuthState{
		csrfToken:     csrfToken,
		codeVerifier:  codeVerifier,
		codeChallenge: codeChallenge,
		expiresAt:     expiresAt,
	}, nil
}

func DTOtoOAuthState(a in.OAuthState) (OAuthState, error) {
	return NewOAuthState(
		a.CsrfToken,
		a.CodeVerifier,
		a.CodeChallenge,
		a.ExpiresAt,
	)
}

// MapToDTO is maping
func (a *OAuthState) MapToDTO() in.OAuthState {
	return in.OAuthState{
		CsrfToken:     a.csrfToken,
		CodeVerifier:  a.codeVerifier,
		CodeChallenge: a.codeChallenge,
		ExpiresAt:     a.expiresAt,
	}
}

func (s OAuthState) CSRFToken() string     { return s.csrfToken }
func (s OAuthState) CodeVerifier() string  { return s.codeVerifier }
func (s OAuthState) CodeChallenge() string { return s.codeChallenge }
func (s OAuthState) ExpiresAt() int64      { return s.expiresAt }

// IsExpired reports whether the state has passed its expiry timestamp.
func (s OAuthState) IsExpired(nowUnix int64) bool {
	return nowUnix > s.expiresAt
}
