basePath: /
definitions:
  http.classifierReqBody:
    properties:
      aphasiaType:
        type: string
      difficulty:
        type: string
    required:
    - aphasiaType
    - difficulty
    type: object
  http.registerReq:
    properties:
      classifier:
        $ref: '#/definitions/http.classifierReqBody'
      email:
        type: string
      fingerprint:
        type: string
      password:
        maxLength: 72
        minLength: 8
        type: string
      role:
        type: string
      verifyCode:
        type: string
    required:
    - classifier
    - email
    - fingerprint
    - password
    - role
    - verifyCode
    type: object
info:
  contact: {}
  description: HTTP API для управления идентификацией и доступом SayMo.
  title: SayMo Identity Service API
  version: "1.0"
paths:
  /iam/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Registration payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.registerReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new account
      tags:
      - Auth
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: 'JWT access token. Формат: Bearer {token}.'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
